version: '3.7'
services:
  ignite-node:
    image: apacheignite/ignite:latest
    container_name: ignite-node-latest
    ports:
      - "10800:10800"
      - "47100:47100"
      - "47500:47500"
      - "49112:49112"
    environment:
      - "IGNITE_HOME=/opt/ignite/apache-ignite"
      - "IGNITE_WORK_DIR=/storage"
      - "IGNITE_PERSISTENCE_ENABLED=true"
      - "CONFIG_URI=/opt/ignite/apache-ignite/config/default-config.xml"
      - "OPTION_LIBS=ignite-rest-http,ignite-log4j2,ignite-spring,ignite-indexing"
      - JAVA_OPTS
        -add-opens=java.base/jdk.internal.access=ALL-UNNAMED
        --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED
        --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
        --add-opens=java.base/sun.util.calendar=ALL-UNNAMED
        --add-opens=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
        --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
        --add-opens=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED
        --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
        --add-opens=java.base/java.io=ALL-UNNAMED
        --add-opens=java.base/java.nio=ALL-UNNAMED
        --add-opens=java.base/java.net=ALL-UNNAMED
        --add-opens=java.base/java.util=ALL-UNNAMED
        --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
        --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
        --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
        --add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
        --add-opens=java.base/java.math=ALL-UNNAMED
        --add-opens=java.sql/java.sql=ALL-UNNAMED
        --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
        --add-opens=java.base/java.time=ALL-UNNAMED
        --add-opens=java.base/java.text=ALL-UNNAMED
        --add-opens=java.management/sun.management=ALL-UNNAMED
        --add-opens java.desktop/java.awt.font=ALL-UNNAMED
    volumes:
      - /home/suyash/test/apachi-ignite/data:/storage
      - /home/suyash/test/apachi-ignite:/opt/ignite/apache-ignite/config
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    command: >
      /opt/ignite/apache-ignite/run.sh
      /opt/ignite/apache-ignite/config/default-config.xml
    entrypoint: >
      /bin/bash -c "
      /opt/ignite/apache-ignite/run.sh /opt/ignite/apache-ignite/config/default-config.xml &&
      /opt/ignite/apache-ignite/bin/control.sh --activate
      "
    networks:
      - ignite-network
    restart: always

networks:
  ignite-network:
    driver: bridge
